#!/bin/bash

color='\e[1;31;44m'   #Red on Blue
#color='\e[1;44;31m' #Blue on Red
NC='\e[0m' # No Color

echo -e "${color}                                                               ${NC}"
echo -e "${color}      __                                                       ${NC}"
echo -e "${color}     /  l                                                      ${NC}"
echo -e "${color}   .'   :               __.....__..._  ____                    ${NC}"
echo -e "${color}  /  /   \\          _.-\"        \"-.  \"\"    \"-.                 ${NC}"
echo -e "${color} (\`-: .---:    .--.'          _....J.         \"-.              ${NC}"
echo -e "${color}  \"\"\"y     \\,.'    \\  __..--\"\"       \`+\"\"--.     \`.            ${NC}"
echo -e "${color}    :     .'/    .-\"\"\"-. _.            \`.   \"-.    \`._.._      ${NC}"
echo -e "${color}    ;  _.'.'  .-j       \`.               \\     \"-.   \"-._\`.    ${NC}"
echo -e "${color}    :    / .-\" :          \\  \`-.          \`-      \"-.      \\   ${NC}"
echo -e "${color}     ;  /.'    ;          :;               .\"        \\      \`, ${NC}"
echo -e "${color}     :_:/      ::\\        ;:     (        /   .-\"   .')      ; ${NC}"
echo -e "${color}       ;-\"      ; \"-.    /  ;           .^. .'    .' /    .-\"  ${NC}"
echo -e "${color}      /     .-  :    \`. '.  : .- / __.-j.'.'   .-\"  /.---'     ${NC}"
echo -e "${color}     /  /      \`,\\.  .'   \"\":'  /-\"   .'       \\__.'           ${NC}"
echo -e "${color}    :  :         ,\\\"\"       ; .'    .'      .-\"\"               ${NC}"
echo -e "${color}   _J  ;         ; \`.      /.'    _/    \\.-\"                   ${NC}"
echo -e "${color}  /  \"-:        /\"--.b-..-'     .'       ;                     ${NC}"
echo -e "${color} /     /  \"\"-..'            .--'.-'/  ,  :                     ${NC}"
echo -e "${color}:\`.   :     / :             \`\\ \" ,',_:  _ \\                    ${NC}"
echo -e "${color}:  \\  '._  :__;             .'.-\"; ; ; j \`.l                   ${NC}"
echo -e "${color} \\  \\          \"-._         \`\"  :_/ :_/                        ${NC}"
echo -e "${color}  \`.;\\             \"-._                                        ${NC}"
echo -e "${color}    :_\"-._             \"-.                                     ${NC}"
echo -e "${color}      \`.  l \"-.     )     \`.                                   ${NC}"
echo -e "${color}        \"\"^--\"\"^-. :        \\                                  ${NC}"
echo -e "${color}                  \";         \\                                 ${NC}"
echo -e "${color}                  :           \`._                              ${NC}"
echo -e "${color}                  ; /    \\ \`._   \"\"---.                        ${NC}"
echo -e "${color}                 / /   _      \`.--.__.'                        ${NC}"
echo -e "${color}                : :   / ;  :\".  \\                              ${NC}"
echo -e "${color}                ; ;  :  :  ;  \`. \`.                            ${NC}"
echo -e "${color}               /  ;  :   ; :    \`. \`.                          ${NC}"
echo -e "${color}              /  /:  ;   :  ;     \"-'                          ${NC}"
echo -e "${color}             :_.' ;  ;    ; :                                  ${NC}"
echo -e "${color}                 /  /     :_l                                  ${NC}"
echo -e "${color}                 \`-'                                           ${NC}"
